name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for finding out an issue or a feature in the Repo DSA, we will work towards it to resolve soon"
        pr-message: "Thanks for contributing in the project for the first time, don't stop yourself and keep on contributing, your pull request will be reviewed soon"
